# Generated by Django 5.2 on 2025-04-15 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MAIN', '0002_remove_landrequest_city_remove_landrequest_country_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='landrequest',
            name='area_name',
        ),
    ]
